@config
@_book=Oracula
@author=Oracula Sibyllina
@availableStructure=book
@compiler=Ernst Boogert
@edition=Die Oracula Sibyllina, Die griechischen christlichen Schriftsteller, Johannes Geffcken, Oracula Sibyllina, J. C. Hinrichs'sche Bechhandlung, Leipzig, 1902, 8.
@editor=Johannes Geffcken
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,book
@sectionTypes=_book,book
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,book
@structureTypes=_book,book
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg1551.tlg001.opp-grc1
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:32:59Z

