@config
@_book=Deuteronomium
@author=Septuaginta
@availableStructure=chapter,verse
@compiler=Ernst Boogert
@edition=The Old Testament in Greek, Genesis - IV Kings, Henry Barclay Swete, Septuaginta, University Press, Cambridge, 1901, 1, Rigaudon hOCR output, Internet Archive.
@editor=Henry Barclay Swete
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=Available under a Creative Commons Attribution-ShareAlike 4.0 International License
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter,verse
@sectionTypes=_book,chapter,verse
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter,verse
@structureTypes=_book,chapter,verse
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg0527.tlg005.opp-grc2
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:32:15Z

