@config
@_book=New Testament - Philippians
@author=not provided
@availableStructure=chapter,verse
@compiler=Ernst Boogert
@edition=The New Testament in the original Greek, 26007333, The text revised by, Brooke Foss Westcott, D.D, Fenton John Anthony Hort, D.D, New York, Harper amp Brothers, Franklin Square, 1882.
@editor=Brooke Foss Westcott, Fenton John Anthony Hort
@fmt:text-orig-beta-plain={beta_plain} 
@fmt:text-orig-full={orig} 
@fmt:text-orig-lemma={lemma} 
@fmt:text-orig-main={main} 
@fmt:text-orig-norm={norm} 
@fmt:text-orig-plain={plain} 
@institution=Protestant Theological University (PThU) Amsterdam/Groningen, The Netherlands
@lang=grc
@license=not provided by source
@name=Patristic corpus from Perseus
@purpose=Making Perseus TEI formatted text available in TF
@sectionFeatures=_book,chapter,verse
@sectionTypes=_book,chapter,verse
@source1=Perseus Digital Library
@source2=Open Greek and Latin Project
@status=initial unchecked conversion
@structureFeatures=_book,chapter,verse
@structureTypes=_book,chapter,verse
@url1=https://github.com/PerseusDL/canonical-greekLit
@url2=https://github.com/OpenGreekAndLatin/First1KGreek
@urn=urn:cts:greekLit:tlg0031.tlg011.perseus-grc2
@valueType=int
@version=1.0
@writtenBy=Text-Fabric
@dateWritten=2019-07-10T11:30:30Z

